Models/Contato.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mvc_frontend.Models
{
    public class Contato
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public bool Active { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace mvc_frontend.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mvc_frontend.Context;
using mvc_frontend.Models;

namespace mvc_frontend.Controllers
{
  public class ContatoController : Controller
  {

    private readonly AgendaContext _context;

    public ContatoController(AgendaContext context)
    {
      _context = context;
    }
    public IActionResult Index()
    {
      var contacts = _context.Contatos.ToList();
      return View(contacts);
    }

    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public IActionResult Create(Contato contact)
    {
      if (ModelState.IsValid)
      {
        _context.Contatos.Add(contact);
        _context.SaveChanges();
        return RedirectToAction(nameof(Index));
      }
      return View(contact);
    }

    public IActionResult Edit(int id)
    {
      var contato = _context.Contatos.Find(id);

      if (contato == null)
        return NotFound();

      return View();
    }

    [HttpPost]
    public IActionResult Edit(Contato contact)
    {
      var contactData = _context.Contatos.Find(contact.Id);

      contactData.Name = contact.Name;
      contactData.PhoneNumber = contact.PhoneNumber;
      contactData.Active = contact.Active;

      _context.Contatos.Update(contactData);
      _context.SaveChanges();

      return RedirectToAction(nameof(Index));
    }

    public IActionResult Details(int id)
    {
      var contact = _context.Contatos.Find(id);

      if (contact == null)
        return RedirectToAction(nameof(Index));

      return View(contact);

    }


    public IActionResult Delete(int id)
    {
      var contact = _context.Contatos.Find(id);

      if (contact == null)
        return RedirectToAction(nameof(Index));

      return View(contact);
    }

    [HttpPost]
    public IActionResult Delete(Contato contact)
    {
      var ContactData = _context.Contatos.Find(contact.Id);
      _context.Contatos.Remove(ContactData);
      _context.SaveChanges();

      return RedirectToAction(nameof(Index));
    }
  }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using mvc_frontend.Models;

namespace mvc_frontend.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Contato/Create.cshtml
@model mvc_frontend.Models.Contato;

@{
    ViewData["Title"] = "Create Contact";
}

<h1>Create New Contact</h1>

</hr>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Active" class="control-label"></label>
                <input type="checkbox" asp-for="Active" class="form-check-input" />
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</hr>
<br>
<div>
    <a asp-action="Index">Back</a>
</div>

Views/Contato/Delete.cshtml
@model mvc_frontend.Models.Contato;

@{
    ViewData["Title"] = "Delete Contact";
}

<h1 style="color: red;">Do you really want to delete this contact?This operation is irreversible.</h1>


</hr>


<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Name)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Name)
        </dt>
                <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.PhoneNumber)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.PhoneNumber)
        </dt>
                <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Active)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Active)
        </dt>
    </dl>
</div>

<form asp-action="Delete">
    <input type="submit" value="Delete" class="btn btn-danger">
</form>
<br>
<a asp-action="Index">Back</a>

Views/Contato/Details.cshtml
@model mvc_frontend.Models.Contato;

@{
    ViewData["Title"] = "Contact Details";
}

<h1>Details</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Name)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Name)
        </dt>
                <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.PhoneNumber)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.PhoneNumber)
        </dt>
                <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Active)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Active)
        </dt>
    </dl>
</div>

<a asp-action="Edit" asp-route-id= "@Model.Id">Edit</a> |
<a asp-action="Index">Back</a>

Views/Contato/Edit.cshtml
@model mvc_frontend.Models.Contato;

@{
    ViewData["Title"] = "Edit Contact";
}

<h1>Edit Contact</h1>

</hr>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Active" class="control-label"></label>
                <input type="checkbox" asp-for="Active" class="form-check-input" />
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</hr>
<br>
<div>
    <a asp-action="Index">Back</a>
</div>

Views/Contato/Index.cshtml
@model IEnumerable<mvc_frontend.Models.Contato>

@{
    ViewData["Title"] = "Contact List";
}

<h2>Contacts</h2>

<p>
    <a asp-action="Create">New Contact</a>
</p>


<table class="table">
    <thead>
        <tr>
            <th>
            @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Active)
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(model => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Active)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>

</table> 

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc_frontend</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvc_frontend.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc_frontend</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato"
                                asp-action="Index">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - mvc_frontend (adony-lagares) - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>